---
version: "2"

services:

  cassandra:
    image: t0mmyt/cassandra
    ports:
      - 127.0.0.1:9042:9042
      - 127.0.0.1:9160:9160
    volumes:
      - ./data/cassandra:/opt/apache-cassandra-3.9/data

  kairosdb:
    image: t0mmyt/kairosdb
    depends_on:
      - cassandra
    ports:
      - 127.0.0.1:8083:8080

  obsloader:
    image: seismic/obsloader
    depends_on:
      - tsdatastore
    ports:
      - 127.0.0.1:8002:8000
    environment:
      - DSHOST=tsdatastore
      - DSPORT=8000

  tsdatastore:
    image: seismic/tsdatastore
    depends_on:
      - kairosdb
    ports:
      - 127.0.0.1:8003:8000
    environment:
      - DBHOST=kairosdb
      - DBPORT=8080

  # sax:
  #   image: seismic/sax
  #   depends_on:
  #     - tsdatastore
  #   ports:
  #     - 127.0.0.1:8004:8000
  #   environment:
  #     - DSHOST=tsdatastore
  #     - DSPORT=8000
