---
version: "2"

services:

  cassandra:
    image: t0mmyt/cassandra
    ports:
      - 9042:9042
      - 9160:9160

  kairosdb:
    image: t0mmyt/kairosdb
    depends_on:
      - cassandra
    ports:
      - 8083:8080

  tsdatastore:
    image: seismic/tsdatastore
    depends_on:
      - kairosdb
    ports:
      - 8003:8000
    environment:
      - DBHOST=kairosdb
      - DBPORT=8080

  obsloader:
    image: seismic/obsloader
    depends_on:
      - tsdatastore
    ports:
      - 8002:8000
    environment:
      - DSHOST=tsdatastore
      - DSPORT=8000
