---
version: "2"

services:

  cassandra:
    image: t0mmyt/cassandra
    ports:
      - 127.0.0.1:9042:9042
      - 127.0.0.1:9160:9160
    volumes:
      - ./data/cassandra:/opt/apache-cassandra-3.9/data

  kairosdb:
    image: t0mmyt/kairosdb
    depends_on:
      - cassandra
    ports:
      - 127.0.0.1:8080:8080

  tsdatastore:
    image: seismic/tsdatastore
    depends_on:
      - kairosdb
    ports:
      - 127.0.0.1:8163:8163
    environment:
      - LISTEN_PORT=8163
      - DB_URL=http://kairosdb:8080

  obsloader:
    image: seismic/obsloader
    depends_on:
      - tsdatastore
    ports:
      - 127.0.0.1:8164:8164
    environment:
      - LISTEN_PORT=8164
      - TSDATASTORE=http://tsdatastore:8163

  interface:
    image: seismic/interface
    depends_on:
      - tsdatastore
      - obsloader
      - sax
    ports:
      - 127.0.0.1:8180:8180
    environment:
      - LISTEN_PORT=8180
      - OBSLOADER=http://obsloader:8164
      - SAX=http://sax:8165
      - TSDATASTORE=http://tsdatastore:8163

  sax:
     image: seismic/sax
     depends_on:
       - tsdatastore
     ports:
       - 127.0.0.1:8165:8165
     environment:
       - LISTEN_PORT=8165
       - TSDATASTORE=http://tsdatastore:8163

  redis:
    image: redis:3.0
    ports:
      - 127.0.0.1:6379:6379